# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SeedPlus
email: hello@seedplus.com
description: > # this means to ignore newlines until "baseurl:"
  A new kind of seed venture firm: A one-of-a-kind network, bigger checks and with founders every day.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.seedplus.com" # the base hostname & protocol for your site
linkedin-url: "https://www.linkedin.com/company/seedplus"
twitter-url: "https://twitter.com/seedplusvc"

# Build settings
markdown: kramdown
plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

collections:
  sessions:
    output: false
  clips:
    output: false
  notes:
    output: true
    permalink: '/calendar/:title'
  portfolio:
    output: false

defaults:
  - scope:
      path: ''
    values:
      excerpt_separator: <!--MAGIC_END_EXCERPT-->
  - scope:
      path: ''
      type: 'notes'
    values:
      layout: note

# Prose (prose.io) configuration (https://github.com/prose/prose/wiki/Prose-Configuration)
prose:
  metadata:
    _sessions:
      - name: title
        field:
          element: text
          label: Event title
      - name: date
        field:
          element: text
          label: Event date
          value: CURRENT_DATETIME
      - name: tag
        field:
          element: select
          label: Tag
          options:
            - name: 'AI/ML'
              value: 'aiml'
            - name: 'Growth'
              value: 'growth'
            - name: 'Fintech'
              value: 'fintech'
            - name: 'Project Alpha'
              value: 'alpha'
      - name: 'exclusive'
        field:
          element: checkbox
          label: 'Is this an exclusive (password-protected) event?'
          value: false
    _clips:
      - name: title
        field:
          element: text
          label: Title of the clip (typically copied verbatim and edited for brevity)
      - name: date
        field:
          element: text
          label: Publishing date
          value: CURRENT_DATETIME
      - name: link
        field:
          element: text
          label: Full URL to the original clip
      - name: outlet
        field:
          element: text
          label: Name of the outlet that published the clip
      - name: tag
        field:
          element: select
          label: Tag
          options:
            - name: 'None'
              value: ''
            - name: 'AI/ML'
              value: 'aiml'
            - name: 'Growth'
              value: 'growth'
            - name: 'Fintech'
              value: 'fintech'
            - name: 'Project Alpha'
              value: 'alpha'
    _notes:
      - name: title
        field:
          element: text
          label: Note title (will be slugified for the URL)
      - name: date
        field:
          element: text
          label: Publishing date
          value: CURRENT_DATETIME
      - name: author
        field:
          element: select
          label: Author
          options:
            - name: 'Michael Smith Jr'
              value: 'michael'
            - name: 'Tiang Lim Foo'
              value: 'tiang'
            - name: 'Gabriel Lundberg'
              value: 'gabriel'
            - name: 'Chirayu Wadke'
              value: 'chirayu'
      - name: tag
        field:
          element: select
          label: Tag
          options:
            - name: 'AI/ML'
              value: 'aiml'
            - name: 'Growth'
              value: 'growth'
            - name: 'Fintech'
              value: 'fintech'
            - name: 'Project Alpha'
              value: 'alpha'
  siteurl: "http://www.seedplus.com"
  media: "/images/upload"
  ignore:
    - /_data
    - /_layouts
    - /_includes
    - /_sass
    - /images
    - .gitignore
    - CNAME
    - _config.yml
    - index.html
    - main.scss