# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SeedPlus
email: hello@seedplus.com
description: > # this means to ignore newlines until "baseurl:"
  A new kind of seed venture firm: A one-of-a-kind network, bigger checks and with founders every day.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.seedplus.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
